platform :ios, '13.0'

target 'Kindling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kindling

  target 'KindlingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Fakery'
  end

end
