platform :ios, '13.0'

target 'Kindling-Cocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kindling-Cocoapods
  pod 'Alamofire', '5.2'
  pod 'SwiftyJSON', '4.0'

  target 'Kindling-CocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMock', '~> 3.7'
  end

end
