# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kindling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kindling
  pod 'CocoaLumberjack/Swift', '3.6.1'
  pod 'RxSwift', '~> 5'
  pod 'RxGesture', '~> 3'
  pod 'RxCocoa', '~> 5'

  target 'KindlingTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
