platform :ios, '13.0'

target 'Kindling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'

  # Pods for Kindling

  target 'KindlingTests' do
    inherit! :search_paths
    pod 'Fakery'
  end

end
